/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mycompany.avanzada;
import java.io.*;
import ventanas.*;


public class App {
   
	public static void main(String arg[]) throws IOException {
                /*
		 //variable para que el usuario escoja en el menu
		String a; // a: almacena lo que el usuario ingrese antes de transformarlo a int
		BufferedReader lector = new BufferedReader(new InputStreamReader(System.in));//se inicializa lector para leer input
		*/
		ppal ventana = new ppal();
                Bodega bodega = new Bodega();
                ventana.init(bodega);
                ventana.setVisible(true);
   }
}