/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Proyecto.programacion.avanzada;
import java.io.*;

public class App {
   public static void main(String arg[]) throws IOException {
	int opcion;
	BufferedReader lector = new BufferedReader(new InputStreamReader(System.in));
	do {
            System.out.println("Seleccione la operacion a realizar");
            opcion=Integer.parseInt(lector.readLine());
	}while(opcion!=0);
    }
}

