/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import com.mycompany.avanzada.Bodega;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Sashi
 */
public class ppal extends javax.swing.JFrame {

   Bodega bodega;

    /**
     * 
     * Creates new form ppal
     * @throws java.io.FileNotFoundException
     */
    //protected int estado;
    public ppal() throws FileNotFoundException {
        initComponents();
    }
    

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BEnlPro = new javax.swing.JButton();
        BVenPro = new javax.swing.JButton();
        BCerrar = new javax.swing.JButton();
        BEmiRep = new javax.swing.JButton();
        BEnlStoDis = new javax.swing.JButton();
        BEliPro = new javax.swing.JButton();
        BModPro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Jokerman", 0, 36)); // NOI18N
        jLabel1.setText("SUPERMERCADO NELDIECA");
        jLabel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(), null));

        BEnlPro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BEnlPro.setText("Enlistar productos");
        BEnlPro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BEnlPro.setContentAreaFilled(false);
        BEnlPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEnlProActionPerformed(evt);
            }
        });

        BVenPro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BVenPro.setText("Vender producto");
        BVenPro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BVenPro.setContentAreaFilled(false);
        BVenPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BVenProActionPerformed(evt);
            }
        });

        BCerrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BCerrar.setText("X");
        BCerrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BCerrar.setContentAreaFilled(false);
        BCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCerrarActionPerformed(evt);
            }
        });

        BEmiRep.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BEmiRep.setText("Emitir reporte");
        BEmiRep.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BEmiRep.setContentAreaFilled(false);
        BEmiRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEmiRepActionPerformed(evt);
            }
        });

        BEnlStoDis.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BEnlStoDis.setText("Enlistar stock distribuidores");
        BEnlStoDis.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BEnlStoDis.setContentAreaFilled(false);
        BEnlStoDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEnlStoDisActionPerformed(evt);
            }
        });

        BEliPro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BEliPro.setText("Eliminar producto");
        BEliPro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BEliPro.setContentAreaFilled(false);
        BEliPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEliProActionPerformed(evt);
            }
        });

        BModPro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BModPro.setText("Modificar producto");
        BModPro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BModPro.setContentAreaFilled(false);
        BModPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BModProActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BEmiRep, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157)
                        .addComponent(BModPro, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BVenPro, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BEliPro, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(BEnlPro, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BEnlStoDis, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(BCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BCerrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BEnlPro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BEnlStoDis, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BVenPro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BEliPro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BEmiRep, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BModPro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(160, 160, 160))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BEnlProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEnlProActionPerformed
        // TODO add your handling code here:
        //bodega.enlistarSecciones();
       try {
           
           new ventanaEnlistar().setVisible(true);
           this.dispose();
       } catch (FileNotFoundException ex) {
           Logger.getLogger(ppal.class.getName()).log(Level.SEVERE, null, ex);
       }

    }//GEN-LAST:event_BEnlProActionPerformed

    private void BVenProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVenProActionPerformed
        // TODO add your handling code here:
        new ventanaVender().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_BVenProActionPerformed

    private void BCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCerrarActionPerformed
        // TODO add your handling code here:
        //GUARDAR
        
    	this.dispose();
        System.exit(0);
    }//GEN-LAST:event_BCerrarActionPerformed

    private void BEmiRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEmiRepActionPerformed
        // TODO add your handling code here:
        new ventanaEmitirReporte().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BEmiRepActionPerformed

    private void BEnlStoDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEnlStoDisActionPerformed
       try {
           // TODO add your handling code here:
           new ventanaEnlistarDistribuidores().setVisible(true);
       } catch (FileNotFoundException ex) {
           Logger.getLogger(ppal.class.getName()).log(Level.SEVERE, null, ex);
       }
        this.dispose();

    }//GEN-LAST:event_BEnlStoDisActionPerformed

    private void BEliProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliProActionPerformed
        // TODO add your handling code here:
        new ventanaEliminarProd().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_BEliProActionPerformed

    private void BModProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BModProActionPerformed
        // TODO add your handling code here:
        new ventanaModificar().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BModProActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ppal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ppal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ppal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ppal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Bodega bodega;
                try {
                    bodega = new Bodega();
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(ppal.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    new ppal().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(ppal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCerrar;
    private javax.swing.JButton BEliPro;
    private javax.swing.JButton BEmiRep;
    private javax.swing.JButton BEnlPro;
    private javax.swing.JButton BEnlStoDis;
    private javax.swing.JButton BModPro;
    private javax.swing.JButton BVenPro;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
