/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import com.mycompany.avanzada.Bodega;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author Sashi
 */
public class ppal extends javax.swing.JFrame {

   Bodega bodega;

    /**
     * 
     * Creates new form ppal
     * @throws java.io.FileNotFoundException
     */
    //protected int estado;
    public ppal() throws FileNotFoundException {
        initComponents();
    }
    
    public void init(Bodega bodega){
        this.bodega = bodega;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        BotonEnlistarProd = new javax.swing.JButton();
        BotonVenderProductos = new javax.swing.JButton();
        BCerrar = new javax.swing.JButton();
        BotonEmitirReporteTxt = new javax.swing.JButton();
        BotonEnlistarStockDist = new javax.swing.JButton();
        BotonElimProd = new javax.swing.JButton();
        BotonModProd = new javax.swing.JButton();
        BotonComprarADist = new javax.swing.JButton();
        BotonEmitirReporteVenta = new javax.swing.JButton();

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Reporte emitido con exito! :)");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addGap(55, 55, 55))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        titulo.setFont(new java.awt.Font("Jokerman", 0, 36)); // NOI18N
        titulo.setText("SUPERMERCADO DIECANEL");
        titulo.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(), null));

        BotonEnlistarProd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BotonEnlistarProd.setText("Enlistar productos");
        BotonEnlistarProd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonEnlistarProd.setContentAreaFilled(false);
        BotonEnlistarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEnlistarProdActionPerformed(evt);
            }
        });

        BotonVenderProductos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BotonVenderProductos.setText("Vender productos");
        BotonVenderProductos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonVenderProductos.setContentAreaFilled(false);
        BotonVenderProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVenderProductosActionPerformed(evt);
            }
        });

        BCerrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BCerrar.setText("X");
        BCerrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BCerrar.setContentAreaFilled(false);
        BCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCerrarActionPerformed(evt);
            }
        });

        BotonEmitirReporteTxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BotonEmitirReporteTxt.setText("Emitir reporte de bodega.txt");
        BotonEmitirReporteTxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonEmitirReporteTxt.setContentAreaFilled(false);
        BotonEmitirReporteTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEmitirReporteTxtActionPerformed(evt);
            }
        });

        BotonEnlistarStockDist.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BotonEnlistarStockDist.setText("Enlistar stock distribuidores");
        BotonEnlistarStockDist.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonEnlistarStockDist.setContentAreaFilled(false);
        BotonEnlistarStockDist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEnlistarStockDistActionPerformed(evt);
            }
        });

        BotonElimProd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BotonElimProd.setText("Eliminar producto");
        BotonElimProd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonElimProd.setContentAreaFilled(false);
        BotonElimProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonElimProdActionPerformed(evt);
            }
        });

        BotonModProd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BotonModProd.setText("Modificar producto");
        BotonModProd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonModProd.setContentAreaFilled(false);
        BotonModProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModProdActionPerformed(evt);
            }
        });

        BotonComprarADist.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BotonComprarADist.setText("Comprar stock a distribuidor");
        BotonComprarADist.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonComprarADist.setContentAreaFilled(false);
        BotonComprarADist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonComprarADistActionPerformed(evt);
            }
        });

        BotonEmitirReporteVenta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BotonEmitirReporteVenta.setText("Emitir reporte de venta");
        BotonEmitirReporteVenta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonEmitirReporteVenta.setContentAreaFilled(false);
        BotonEmitirReporteVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEmitirReporteVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotonEmitirReporteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotonEmitirReporteVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(92, 92, 92)
                                .addComponent(BotonElimProd, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(titulo)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(BotonEnlistarProd, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                        .addComponent(BotonVenderProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(BotonEnlistarStockDist, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(92, 92, 92)
                                            .addComponent(BotonComprarADist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addComponent(BotonModProd, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(BCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BCerrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonEnlistarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonEnlistarStockDist, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonVenderProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonComprarADist, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonEmitirReporteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonModProd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonElimProd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonEmitirReporteVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonEnlistarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEnlistarProdActionPerformed
        // TODO add your handling code here:
        //bodega.enlistarSecciones();
       try {
           new ventanaEnlistar().setVisible(true);
           this.dispose();
       } catch (FileNotFoundException ex) {
           Logger.getLogger(ppal.class.getName()).log(Level.SEVERE, null, ex);
       }

    }//GEN-LAST:event_BotonEnlistarProdActionPerformed

    private void BotonVenderProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVenderProductosActionPerformed
       try {
           /*
           try {
           // TODO add your handling code here:
           //bodega.Venta();
           } catch (IOException ex) {
           Logger.getLogger(ppal.class.getName()).log(Level.SEVERE, null, ex);
           }
           */
           new ventanaVentaSeccion(bodega).setVisible(true);
       } catch (FileNotFoundException ex) {
           Logger.getLogger(ppal.class.getName()).log(Level.SEVERE, null, ex);
       }
        this.dispose();

    }//GEN-LAST:event_BotonVenderProductosActionPerformed

    private void BCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCerrarActionPerformed
        // TODO add your handling code here:
        //GUARDAR
        
    	this.dispose();
        System.exit(0);
    }//GEN-LAST:event_BCerrarActionPerformed

    private void BotonEmitirReporteTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEmitirReporteTxtActionPerformed
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int screenWidth = (int) dim.getWidth();
        int screenHeight = (int) dim.getHeight();
        jDialog1.add( new JLabel ("REPORTEEE"));  
        jDialog1.setSize(400,200);  
        jDialog1.setLocation(screenWidth / 2 - 150, screenHeight / 2 - 150);
        jDialog1.setVisible(true);
        
        try {
            // TODO add your handling code here:
            bodega.getFile().reporteBodega();
        } catch (IOException ex) {
            Logger.getLogger(ppal.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
        this.dispose();
    }//GEN-LAST:event_BotonEmitirReporteTxtActionPerformed

    private void BotonEnlistarStockDistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEnlistarStockDistActionPerformed
        try {
           // TODO add your handling code here:
            ventanaEnlistarDistribuidores ventana = new ventanaEnlistarDistribuidores(bodega);
            ventana.setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ppal.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();

    }//GEN-LAST:event_BotonEnlistarStockDistActionPerformed

    private void BotonElimProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonElimProdActionPerformed
       try {
           // TODO add your handling code here:
           new ventanaElim().setVisible(true);
       } catch (FileNotFoundException ex) {
           Logger.getLogger(ppal.class.getName()).log(Level.SEVERE, null, ex);
       }
        this.dispose();

    }//GEN-LAST:event_BotonElimProdActionPerformed

    private void BotonModProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModProdActionPerformed
        try {
            // TODO add your handling code here:
            ventanaModi ventana = new ventanaModi(bodega);
            ventana.setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ppal.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_BotonModProdActionPerformed

    private void BotonComprarADistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonComprarADistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonComprarADistActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jDialog1.dispose();
        ppal ventana;
        try {
            ventana = new ppal();
            ventana.init(bodega);
            ventana.setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ppal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BotonEmitirReporteVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEmitirReporteVentaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ventanaEmitirReporte ventana = new ventanaEmitirReporte();
        ventana.init(bodega);
        ventana.setVisible(true);
    }//GEN-LAST:event_BotonEmitirReporteVentaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCerrar;
    private javax.swing.JButton BotonComprarADist;
    private javax.swing.JButton BotonElimProd;
    private javax.swing.JButton BotonEmitirReporteTxt;
    private javax.swing.JButton BotonEmitirReporteVenta;
    private javax.swing.JButton BotonEnlistarProd;
    private javax.swing.JButton BotonEnlistarStockDist;
    private javax.swing.JButton BotonModProd;
    private javax.swing.JButton BotonVenderProductos;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
