/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import com.mycompany.avanzada.Bodega;
import com.mycompany.avanzada.Distribuidores;
import com.mycompany.avanzada.ProdDistrib;
import com.mycompany.avanzada.StockAmountException;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Arrays;
import java.util.Map;
import java.util.Map.Entry;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author sadri
 */
public class ventantaCompraDist extends javax.swing.JFrame {

    /**
     * Creates new form ventantaCompraDist
     */
    Bodega bodega;

    public ventantaCompraDist(Bodega bodega) throws FileNotFoundException {
        this.bodega = bodega;
        initComponents();
        this.generarComboBox1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        bOkDialog2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Distribuidores = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        Productos = new javax.swing.JComboBox<>();
        min = new javax.swing.JLabel();
        Slider = new javax.swing.JSlider();
        max = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonFinalizarCo = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel5.setText("Agregado! :)");

        bOkDialog2.setText("Ok");
        bOkDialog2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOkDialog2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bOkDialog2)
                .addContainerGap())
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel5)
                .addContainerGap(173, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(71, 71, 71)
                .addComponent(bOkDialog2)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel1.setText("Seleccione la seccion del producto que busca");

        Distribuidores.setToolTipText("");
        Distribuidores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DistribuidoresItemStateChanged(evt);
            }
        });
        Distribuidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DistribuidoresActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel2.setText("Seleccione producto");

        Productos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ProductosItemStateChanged(evt);
            }
        });
        Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductosActionPerformed(evt);
            }
        });

        min.setText("0");

        Slider.setMaximum(0);
        Slider.setPaintLabels(true);
        Slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderStateChanged(evt);
            }
        });
        Slider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SliderMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SliderMousePressed(evt);
            }
        });

        max.setText("0");

        jLabel4.setText("Cantidad actual:");

        jLabel3.setText("?");

        botonFinalizarCo.setText("Finalizar compra");
        botonFinalizarCo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFinalizarCoActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        jButton2.setText("X");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                        .addComponent(min)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(botonFinalizarCo)
                                .addGap(18, 18, 18)
                                .addComponent(botonAceptar)
                                .addGap(27, 27, 27))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3)
                                    .addGap(185, 185, 185))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Slider, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(max)
                                    .addGap(74, 74, 74)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(Distribuidores, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Distribuidores, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(min)
                            .addComponent(max))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonFinalizarCo)
                            .addComponent(botonAceptar))
                        .addGap(14, 14, 14))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DistribuidoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DistribuidoresItemStateChanged
        try {
            // TODO add your handling code here:
            generarComboBox2();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ventanaVentaSeccion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DistribuidoresItemStateChanged

    private void DistribuidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DistribuidoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DistribuidoresActionPerformed

    private void ProductosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ProductosItemStateChanged
        String keyDis = (String) Distribuidores.getSelectedItem();
        String keyProd = (String) Productos.getSelectedItem();
        Map<String, Distribuidores> dist = bodega.getMapaDist();
        Map<String, ProdDistrib> prods = dist.get(keyDis).getMapaD();
        ProdDistrib prodActual = prods.get(keyProd);

        Slider.setMaximum(prodActual.getStock());
        if (prodActual.getStock() <= 0) {
            min.setText("0");
            Slider.setMinimum(0);
        } else {
            min.setText("1");
            Slider.setMinimum(1);
        }
        int maximo = prodActual.getStock();
        max.setText(Integer.toString(maximo));

    }//GEN-LAST:event_ProductosItemStateChanged

    private void SliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderStateChanged
        int num = Slider.getValue();
        jLabel3.setText(Integer.toString(num));
    }//GEN-LAST:event_SliderStateChanged

    private void SliderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SliderMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_SliderMouseClicked

    private void SliderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SliderMousePressed

    }//GEN-LAST:event_SliderMousePressed

    private void botonFinalizarCoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFinalizarCoActionPerformed
        try {
            // TODO add your handling code here:
            bodega.finalizarVenta(bodega.getOrdenCom());
            ppal ventana = new ppal();
            ventana.init(bodega);
            ventana.setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ventanaVentaSeccion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ventanaVentaSeccion.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_botonFinalizarCoActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
        String dis = (String) Distribuidores.getSelectedItem();
        String prod = (String) Productos.getSelectedItem();
        int cant = Slider.getValue();
        try {
            bodega = bodega.comprarDitrib(dis, prod, cant, bodega);
        } catch (IOException ex) {
            Logger.getLogger(ventanaVentaSeccion.class.getName()).log(Level.SEVERE, null, ex);
        }catch (StockAmountException eS) {
        	JOptionPane.showMessageDialog(null,"Error: Stock insuficiente");
        }

        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int screenWidth = (int) dim.getWidth();
        int screenHeight = (int) dim.getHeight();

        jDialog1.add(new JLabel("Agregado! :)"));
        jDialog1.setLocation(screenWidth / 2 - 150, screenHeight / 2 - 150);
        jDialog1.setSize(400, 200);
        jDialog1.setVisible(true);
        //setVisible(true);
        //bOkDialog; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            // TODO add your handling code here:
            ppal ventana = new ppal();
            ventana.setVisible(true);
            ventana.init(bodega);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ventanaVentaSeccion.class.getName()).log(Level.SEVERE, null, ex);
        }

        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductosActionPerformed

    private void bOkDialog2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOkDialog2ActionPerformed
        // TODO add your handling code here:
        jDialog1.dispose();
    }//GEN-LAST:event_bOkDialog2ActionPerformed

    private void generarComboBox1() throws FileNotFoundException {
        String[] opciones = new String[bodega.getMapaDist().size()];
        int i = 0;
        for (Map.Entry<String, Distribuidores> r : bodega.getMapaDist().entrySet()) {
            for (Entry<String, ProdDistrib> o : r.getValue().getMapaD().entrySet()) {
                if (!Arrays.asList(opciones).contains(o.getValue().getMarca())) {
                    opciones[i] = o.getValue().getMarca();
                    i++;
                }
            }
        }

        Distribuidores.setModel(new javax.swing.DefaultComboBoxModel(opciones));
        Distribuidores.setSelectedIndex(-1);
    }

    public void generarComboBox2() throws FileNotFoundException {
        if (Distribuidores.getSelectedItem() != null) {
            //conseguir mapa de productos para asignar nombres a opciones de combobox2
            Map<String, Distribuidores> distri = bodega.getMapaDist();
            String key = (String) Distribuidores.getSelectedItem();
            Map<String, ProdDistrib> mapa = distri.get(key).getMapaD();
            String[] opciones = new String[mapa.size() + 1];
            opciones[0] = "Selecionar Producto";
            int i = 1;
            for (Entry<String, ProdDistrib> r : mapa.entrySet()) {
                opciones[i] = r.getValue().getNombre();
                i++;
            }
            Productos.setModel(new javax.swing.DefaultComboBoxModel(opciones));

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Distribuidores;
    private javax.swing.JComboBox<String> Productos;
    private javax.swing.JSlider Slider;
    private javax.swing.JButton bOkDialog;
    private javax.swing.JButton bOkDialog1;
    private javax.swing.JButton bOkDialog2;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonFinalizarCo;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel max;
    private javax.swing.JLabel min;
    // End of variables declaration//GEN-END:variables
}
