/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import com.mycompany.avanzada.Bodega;
import com.mycompany.avanzada.Distribuidores;
import com.mycompany.avanzada.ProdDistrib;
import com.mycompany.avanzada.TipoProducto;
import java.io.FileNotFoundException;
import java.util.Arrays;
import java.util.Map;
import java.util.Map.Entry;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Sashi
 */
public class ventanaModi extends javax.swing.JFrame {

    /**
     * Creates new form ventanaVentaSeccion
     */
    Bodega bodega;
    public ventanaModi(Bodega bodega) throws FileNotFoundException {
        this.bodega = bodega;
        initComponents();
        this.generarComboBox1();
    }
      
    public void generarComboBox1() throws FileNotFoundException{
        String[] opciones = new String[bodega.getMapaDist().size()];
        int i = 0;
        for(Map.Entry<String, Distribuidores> r : bodega.getMapaDist().entrySet()) {
            for(Entry<String, ProdDistrib> o : r.getValue().getMapaD().entrySet()) {                
                if(!Arrays.asList(opciones).contains(o.getValue().getMarca())){
                    opciones[i] = o.getValue().getMarca();
                    i++;     
                }  
            }
 	}
        
        Distribuidores.setModel(new javax.swing.DefaultComboBoxModel(opciones));
        Distribuidores.setSelectedIndex(-1);
    }
    public void generarComboBox2() throws FileNotFoundException{
        if(Distribuidores.getSelectedItem() != null){
            //conseguir mapa de productos para asignar nombres a opciones de combobox2
            Map<String,ProdDistrib> mapa = bodega.getMapaDist().get(Distribuidores.getSelectedItem()).getMapaD();
            String[] opciones = new String[mapa.size()];
            int i = 0;
            for(Entry<String, ProdDistrib> r : mapa.entrySet()) {
        	opciones[i] = r.getValue().getNombre();
    		i++;
            }
            Productos.setModel(new javax.swing.DefaultComboBoxModel(opciones));
        }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Distribuidores = new javax.swing.JComboBox<>();
        Productos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("X");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Distribuidores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DistribuidoresItemStateChanged(evt);
            }
        });

        Productos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ProductosItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel1.setText("Seleccione el distribuidor del producto que busca");

        jLabel2.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel2.setText("Seleccione producto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(Distribuidores, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(141, 357, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(662, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(103, 103, 103)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Distribuidores, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        try {
            // TODO add your handling code here:
            ppal ventana = new ppal();
            ventana.init(bodega);
            ventana.setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ventanaModi.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String d = (String) Distribuidores.getSelectedItem();
        String p = (String) Productos.getSelectedItem();
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void DistribuidoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DistribuidoresItemStateChanged
        try {
            // TODO add your handling code here:
            generarComboBox2();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ventanaModi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DistribuidoresItemStateChanged

    private void ProductosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ProductosItemStateChanged
        // TODO add your handling code here:
        //Slider = new javax.swing.JSlider();
        //Slider.setPaintTicks(true);
        //bodega.getMapa().get(Secciones.getSelectedItem()).getMapa().get(Productos.getSelectedItem()).getStock());
    }//GEN-LAST:event_ProductosItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Distribuidores;
    private javax.swing.JComboBox<String> Productos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
