/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import com.mycompany.avanzada.Bodega;
import com.mycompany.avanzada.Distribuidores;
import com.mycompany.avanzada.ProdDistrib;
import com.mycompany.avanzada.TipoProducto;
import java.io.FileNotFoundException;
import javax.swing.table.DefaultTableModel;
import java.util.Map.Entry;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Sashi
 */
public final class ventanaEnlistarDistribuidores extends javax.swing.JFrame {

    /**
     * Creates new form ventanaEnlistar
     */
    DefaultTableModel modelo;
    Bodega bodega;
    public ventanaEnlistarDistribuidores(Bodega bodega) throws FileNotFoundException {
        
        initComponents();
        this.bodega = bodega;
        modelo = new DefaultTableModel();
        modelo.addColumn("C1"); 
        modelo.addColumn("C2");
        modelo.addColumn("C3"); 
        modelo.addColumn("C4");
        modelo.addColumn("C5"); 
        modelo.addColumn("C6");
        this.listar();
    }
    
    
    public void listar() throws FileNotFoundException{
        String[] a = new String[6];
        modelo = (DefaultTableModel)Tabla.getModel();
        ProdDistrib now;
        for(Entry<String, Distribuidores> r : bodega.getMapaDist().entrySet()) {
        	for(Entry<String, ProdDistrib> o : r.getValue().getMapaD().entrySet()) {
                    now = (ProdDistrib) o.getValue();
                    /*
                    a[0] = now.getNombre();
                    a[1] = now.getSeccion();
                    a[2] = Integer.toString(now.getCodigo());
                    a[3] = Integer.toString(now.getStock());
                    a[4] = Integer.toString(now.getPrecio());
                    a[5] = now.getMarca();
                    modelo.addRow(a);    
                    */
                    a[0] = now.getMarca();
                    a[1] = now.getNombre();
                    a[2] = Integer.toString(now.getCodigo());
                    a[3] = Integer.toString(now.getStock());
                    a[4] = "$"+Integer.toString(now.getPrecio());
                    a[5] = now.getSeccion();
                    modelo.addRow(a); 
    		}
 	}
        Tabla.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jButton2.setText("X");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Distribuidor", "Nombre", "Codigo", "Stock", "Precio unitario", "Categoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            ppal ventana = new ppal();
            ventana.init(bodega);
            ventana.setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ventanaEnlistarDistribuidores.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();

    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    

}
